owner: NASA-IMPACT
repo: csdap-status

sites:
  - name: Smallsat Data Explorer (SDX)
    url: https://csdap.earthdata.nasa.gov
  - name: STAC API
    url: https://csdap.earthdata.nasa.gov/stac/_mgmt/ping
  - name: Orders API - Server
    url: https://csdap.earthdata.nasa.gov/api/v1/health/server
  - name: Orders API - Database
    url: https://csdap.earthdata.nasa.gov/api/v1/health/db
  - name: Orders API - Data
    url: https://csdap.earthdata.nasa.gov/api/v1/health/data
  - name: Data Authorization System
    url: https://csdap.earthdata.nasa.gov/signup/

status-website:
  # cname: status.csdap.earthdata.nasa.gov
  baseUrl: /csdap-status
  logoUrl: https://csdap.earthdata.nasa.gov/images/CSDA_logo.png
  name: CSDA infrastructure monitor
  introTitle: "**CSDA** program infrastructure monitor."
  introMessage: Uptime monitor for the various services that support the [Commercial Smallsat Data Acquisition (CSDA) Program](https://www.earthdata.nasa.gov/esds/csda).
  navbar:
    - title: Smallsat Data Explorer
      href: https://csdap.earthdata.nasa.gov
    - title: CSDA Program Summary
      href: https://www.earthdata.nasa.gov/esds/csda

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
