owner: NASA-IMPACT
repo: csdap-status

sites:
  - name: SDX
    url: https://csdap.earthdata.nasa.gov
  - name: STAC API
    url: https://csdap.earthdata.nasa.gov/stac/_mgmt/ping
  - name: Orders API - Server
    url: https://csdap.earthdata.nasa.gov/api/v1/health/server
  - name: Orders API - Database
    url: https://csdap.earthdata.nasa.gov/api/v1/health/db
  - name: Orders API - Data
    url: https://csdap.earthdata.nasa.gov/api/v1/health/data
  - name: Data Authorization System
    url: https://csdap.earthdata.nasa.gov/signup

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /csdap-status
  logoUrl: https://csdap.earthdata.nasa.gov/images/CSDA_logo.png
  name: CSDAP Status
  introTitle: "**CSDAP** status monitor."
  introMessage: This page monitors the various services that support the [Commercial Smallsat Data Acquisition (CSDA) Program](https://www.earthdata.nasa.gov/esds/csda).
  navbar:
    - title: Status
      href: /
    - title: SDX
      href: https://csdap.earthdata.nasa.gov
    - title: CSDA Program
      href: https://www.earthdata.nasa.gov/esds/csda
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
